### PR TITLE
clusterlogging pkg: clusterlogging handler adjustments + new methods

### PR DESCRIPTION
**Pull request by elenagerman**
clusterlogging handler adjustments + new methods:

- WithCollection
- WithManagementState
- WithLogStore
- WithVisualization

### CODE REVIEW

**Comment by elenagerman** [comment]
@trewest @kononovn @achuzhoy @cdvultur PTAL

**Comment by elenagerman** [comment]
@trewest @kononovn @achuzhoy @cdvultur PTAL

**Review by kononovn — APPROVED** [review]
/lgtm

**Review by trewest — APPROVED** [review]
/lgtm

**Pull request merged**
