### PR TITLE
Update assisted resources to v0.0.0-20230906121258-6d85fb16f8dd

### PR DESCRIPTION
**Pull request by trewest**
Updates assisted service resources to v0.0.0-20230906121258-6d85fb16f8dd

- Includes changes to InfraEnv CRD
- Includes changes to Agent CRD

### CODE REVIEW

**Comment by kononovn** [comment]
@trewest Please re-base

**Comment by trewest** [comment]
> @trewest Please re-base

Done

**Comment by trewest** [comment]
```
	APIClient := clients.New("")
	asc, err := assisted.PullAgentServiceConfig(APIClient)

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(asc.Definition.Name)
```

```
agent
```
Tested the client works correctly

**Review by kononovn — APPROVED** [review]
lgtm

**Pull request merged**
