### PR TITLE
lifecycleagent package: renaming functions names for imagebasedupgrade.

### PR DESCRIPTION
**Pull request by achuzhoy**
This should hep distinct among the CRs

### CODE REVIEW

**Comment by trewest** [comment]
@achuzhoy ImageBasedUpgrade should also be updated to ImageBasedUpgradeBuilder

**Review by kononovn — DISMISSED** [review]
@achuzhoy Please update commit/PR name. Add package in order to improve readability

**Review by trewest — APPROVED** [review]
/lgtm

**Comment by achuzhoy** [comment]
> @achuzhoy Please update commit/PR name. Add package in order to improve readability

Updated. Thanks.
cc @kononovn

**Review by kononovn — APPROVED** [review]
/lgtm

**Pull request merged**
