### PR TITLE
elasticsearch object handler added + unit tests

### PR DESCRIPTION
**Pull request by elenagerman**
- elasticsearch object handler added
- unit tests elasticsearch

### CODE REVIEW

**Comment by kononovn** [comment]
@elenagerman 
We've merged clusterlogging_test.go please re-base.

Please split this PR in 2 PRs
1 PR for clusterlogforwarder_test.go
2 PR for elasticsearch + test

**Comment by elenagerman** [comment]
> @elenagerman We've merged clusterlogging_test.go please re-base.
> 
> Please split this PR in 2 PRs 1 PR for clusterlogforwarder_test.go 2 PR for elasticsearch + test

@kononovn done

**Comment by elenagerman** [comment]
@kononovn PTAL

**Review by kononovn — APPROVED** [review]
/lgtm

**Pull request merged**
