### PR TITLE
rename bmh builder and file name

### PR DESCRIPTION
**Pull request by elenagerman**
rename bmh Builder to be unique
rename filename (this one includes methods related to the single object handling; at least one more file will be added - handle list of baremetalhosts)

### CODE REVIEW

**Comment by kononovn** [comment]
@elenagerman This change will break most of test cases in test projects. Can we avoid this change ?

**Review by kononovn — CHANGES_REQUESTED** [review]
@elenagerman This change will break most of test cases in test projects because we are changing public object that is in use in most of test suites. Can we avoid this change ?

**Comment by elenagerman** [comment]
> @elenagerman This change will break most of test cases in test projects because we are changing public object that is in use in most of test suites. Can we avoid this change ?

@kononovn I didn't find any test yet which uses this library.
@trewest , for example, for some reason, uses bmhv1alpha1 "github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1" instead of package:
https://github.com/openshift-kni/eco-gotests/blob/main/tests/assisted/ztp/operator/internal/tsparams/operatorvars.go
https://github.com/openshift-kni/eco-gotests/blob/main/tests/assisted/ztp/spoke/internal/tsparams/spokevars.go

I think it will be better to do it now then wait until it will be used by eco-gotests

**Comment by kononovn** [comment]
> @kononovn Please let me know, if you prefer do not rename it anyway, we will close this MR and I will call my new method "list.go' instead of 'baremetalhosts.go'

You are right. This package is not in use so no problem with re-naming. I'll merge it

**Review by kononovn — APPROVED** [review]
lgtm

**Review by trewest — APPROVED** [review]
/lgtm

**Pull request merged**
